openapi: 3.0.0
info:
  title: NoApp API Documentation
  version: 1.0.0
paths:
  /genkey:
    post:
      summary: Generate API Key
      description: Endpoint to generate a new API key for a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                label:
                  type: string
              required:
                - username
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                apiKey: "f0c3f0cf9a58b0c9..."
        '400':
          description: Bad request
          content:
            application/json:
              example:
                error: "Username is required"
        '500':
          description: Internal server error
          content:
            application/json:
              example:
                error: "Database error"
  /getkeys:
    post:
      summary: Get API Keys
      description: Endpoint to retrieve API keys for a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
                - username
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                apiKeys:
                  - "f0c3f0cf9a58b0c9..."
                  - "3f0cf9a58b0c9f0c..."
        '400':
          description: Bad request
          content:
            application/json:
              example:
                error: "Username is required"
        '500':
          description: Internal server error
          content:
            application/json:
              example:
                error: "Database error"
  /deletekey:
    post:
      summary: Delete API Key
      description: Endpoint to delete an API key for a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                apiKey:
                  type: string
              required:
                - username
                - apiKey
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                message: "Record has been deleted"
        '400':
          description: Bad request
          content:
            application/json:
              example:
                error: "Username and API key are required"
        '500':
          description: Internal server error
          content:
            application/json:
              example:
                error: "Database error"
        'default':
          description: Error
          content:
            application/json:
              example:
                message: "Record does not exist"
